### ISSUE TITLE
GPU Memory leak (Opera)

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/chrome-youtube-ambilight#14]
After while the browser tab crashes and restarts without the ambilight effect

**Reported by**
@iGerman00

**Browsers**
Confirmed on
- Opera GX version LVL 1 (core: 64.0.3417.150)
- Opera version 65.0.3467.78

Not reproducible on
- Chrome version 79.0.3945.88 (Official Build) (64-bit)

**Repro steps**
It seems to be caused by a combination of the following 2 settings:
- Ambilight - Spread: >=25.7%
- Ambilight - Edge size >28.5%

**Details**
It might be related to this known Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1015729

**Comment by WesselKroos** [comment]
@iGerman00 Can you confirm that the bug is resolved when you change the following to settings below these values?
- Ambilight - Spread: 25.7%
- Ambilight - Edge size 28.5%

**Comment by iGerman00** [comment]
> resolved

Seems to be that, yes, if I set them both to 20%, the issue goes away. 

However, with those settings, my 21:9 monitor is not fully covered with the ambilight effect, which is what I am going for. Waiting for a fix in the meantime.

**Comment by WesselKroos** [comment]
**Cause:**
The smallest scaled canvas elements behind the video have a layout with of 0x0 when the Spread is above 25.7% and the Edge size is above 28.5%. A canvas with the size 0x0 is not drawn which causes the same bug as a invisible canvas. This GPU memory leak is present in this bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1015729

**Workaround**
I'll give the canvas elements a minimal size of 1x1 so this can never happen regardless of the settings.

**Comment by WesselKroos** [comment]
@iGerman00 I've published a preview of the extension on the Opera webstore containing the fix. Can you validate if that version resolves the issue.
https://addons.opera.com/nl/extensions/details/youtube-ambilight/

PS: I will take a few more days to fully test this new version before I'll update the extension in the Chrome webstore.

**Comment by iGerman00** [comment]
> @iGerman00 I've published a preview of the extension on the Opera webstore containing the fix. Can you validate if that version resolves the issue.
> https://addons.opera.com/nl/extensions/details/youtube-ambilight/
> 
> PS: I will take a few more days to fully test this new version before I'll update the extension in the Chrome webstore.

Sorry for late reply, completely forgot about this.
I can confirm, the issue with the memory leak is gone, even with high values for both these settings. 

**HOWEVER**,

It shifts the entire video in fullscreen or in big player mode (strangely it doesn't shift it in normal mode, but ambilight itself is still shifted). That's why I still cannot use it.
[Enabled](https://i.imgur.com/Qo3nz4D.jpg)
[Disabled](https://i.imgur.com/U1sxQ0U.jpg)


Extension installed from the Opera webstore, Monitor is still 21:9 aspect ratio.

**Comment by WesselKroos** [comment]
Thank you for reporting the initial bug and confirming that this resolved the memory leak!
I've created a new issue for the shifted video.
